# This file is a template, and might need editing before it works on your project.

stages:
  - build
  #- test
  - push
  - deploy

variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA




# Build docker image
build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - apt-get install -y make
  script:
    - make build

# Push docker image to container registry
push:
  image: docker:latest
  stage: push
  services:
    - docker:dind
  before_script:
    - apt-get install -y make
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - make push
  only:
    - main

# Deploy docker image to server and run it
# Deploy to DigitalOcean Droplet at passpredict.com
deploy:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  before_script:
    - apt install -y make
    # Set up SSH
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # Login to container registry
    - ssh gitlab-deploy@passpredict.com docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - make deploy
  when: manual
  only:
    - main

