"""rename satellite column decayed_date to decay_date

Revision ID: 06fe754cdf64
Revises: 75de7b78544d
Create Date: 2021-11-18 16:11:47.247139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06fe754cdf64'
down_revision = '75de7b78544d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('satellite', sa.Column('decay_date', sa.Date(), nullable=True))
    op.drop_column('satellite', 'decayed_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('satellite', sa.Column('decayed_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('satellite', 'decay_date')
    # ### end Alembic commands ###
