"""Add timezone to TLE datetime timestamp

Revision ID: 3d667c57b6f3
Revises: 
Create Date: 2021-10-04 01:33:03.308696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d667c57b6f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satellite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cospar_id', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('decayed', sa.Boolean(), nullable=True),
    sa.Column('launch_date', sa.Date(), nullable=True),
    sa.Column('launch_year', sa.Integer(), nullable=True),
    sa.Column('mass', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('diameter', sa.Float(), nullable=True),
    sa.Column('span', sa.Float(), nullable=True),
    sa.Column('perigee', sa.Float(), nullable=True),
    sa.Column('apogee', sa.Float(), nullable=True),
    sa.Column('inclination', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cospar_id')
    )
    op.create_table('tle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tle1', sa.String(length=70), nullable=True),
    sa.Column('tle2', sa.String(length=70), nullable=True),
    sa.Column('epoch', sa.DateTime(timezone=True), nullable=True),
    sa.Column('satellite_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['satellite_id'], ['satellite.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tle_satellite_id'), 'tle', ['satellite_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tle_satellite_id'), table_name='tle')
    op.drop_table('tle')
    op.drop_table('satellite')
    # ### end Alembic commands ###
