"""Rename foreign key columns on satellite table

Revision ID: 75de7b78544d
Revises: 8cd3a0647450
Create Date: 2021-11-18 15:39:28.750094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75de7b78544d'
down_revision = '8cd3a0647450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('satellite', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('satellite', sa.Column('rcs', sa.Float(), nullable=True))
    op.add_column('satellite', sa.Column('status_id', sa.Integer(), nullable=True))
    op.add_column('satellite', sa.Column('type_id', sa.Integer(), nullable=True))
    op.add_column('satellite', sa.Column('updated', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_satellite_decayed'), 'satellite', ['decayed'], unique=False)
    op.drop_constraint('satellite_type_fkey', 'satellite', type_='foreignkey')
    op.drop_constraint('satellite_status_fkey', 'satellite', type_='foreignkey')
    op.drop_constraint('satellite_owner_fkey', 'satellite', type_='foreignkey')
    op.create_foreign_key(None, 'satellite', 'satellite_status', ['status_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'satellite', 'satellite_owner', ['owner_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'satellite', 'satellite_type', ['type_id'], ['id'], ondelete='SET NULL')
    op.drop_column('satellite', 'owner')
    op.drop_column('satellite', 'status')
    op.drop_column('satellite', 'type')
    op.add_column('satellite_status', sa.Column('short_name', sa.String(length=10), nullable=True))
    op.create_unique_constraint(None, 'satellite_status', ['short_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'satellite_status', type_='unique')
    op.drop_column('satellite_status', 'short_name')
    op.add_column('satellite', sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('satellite', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('satellite', sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'satellite', type_='foreignkey')
    op.drop_constraint(None, 'satellite', type_='foreignkey')
    op.drop_constraint(None, 'satellite', type_='foreignkey')
    op.create_foreign_key('satellite_owner_fkey', 'satellite', 'satellite_owner', ['owner'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('satellite_status_fkey', 'satellite', 'satellite_status', ['status'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('satellite_type_fkey', 'satellite', 'satellite_type', ['type'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_satellite_decayed'), table_name='satellite')
    op.drop_column('satellite', 'updated')
    op.drop_column('satellite', 'type_id')
    op.drop_column('satellite', 'status_id')
    op.drop_column('satellite', 'rcs')
    op.drop_column('satellite', 'owner_id')
    # ### end Alembic commands ###
