"""Add satellite_id index to Tle table

Revision ID: 77b98ec92dd9
Revises: cfb3e25518d0
Create Date: 2020-11-08 13:34:12.982275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b98ec92dd9'
down_revision = 'cfb3e25518d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tle_satellite_id'), 'tle', ['satellite_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tle_satellite_id'), table_name='tle')
    # ### end Alembic commands ###
