"""Add satellite columns and related foreign key tables

Revision ID: 8cd3a0647450
Revises: 3d667c57b6f3
Create Date: 2021-11-18 10:59:07.452931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd3a0647450'
down_revision = '3d667c57b6f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('launch_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('satellite_owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('satellite_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('satellite_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('short_name')
    )
    op.add_column('satellite', sa.Column('decayed_date', sa.Date(), nullable=True))
    op.add_column('satellite', sa.Column('launch_site_id', sa.Integer(), nullable=True))
    op.add_column('satellite', sa.Column('owner', sa.Integer(), nullable=True))
    op.add_column('satellite', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('satellite', sa.Column('type', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'satellite', 'satellite_status', ['status'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'satellite', 'satellite_type', ['type'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'satellite', 'satellite_owner', ['owner'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'satellite', 'launch_site', ['launch_site_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'satellite', type_='foreignkey')
    op.drop_constraint(None, 'satellite', type_='foreignkey')
    op.drop_constraint(None, 'satellite', type_='foreignkey')
    op.drop_constraint(None, 'satellite', type_='foreignkey')
    op.drop_column('satellite', 'type')
    op.drop_column('satellite', 'status')
    op.drop_column('satellite', 'owner')
    op.drop_column('satellite', 'launch_site_id')
    op.drop_column('satellite', 'decayed_date')
    op.drop_table('satellite_type')
    op.drop_table('satellite_status')
    op.drop_table('satellite_owner')
    op.drop_table('launch_site')
    # ### end Alembic commands ###
