"""add satellite period column

Revision ID: ac58d65c5667
Revises: 06fe754cdf64
Create Date: 2021-11-18 17:29:36.896979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac58d65c5667'
down_revision = '06fe754cdf64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('satellite', sa.Column('period', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('satellite', 'period')
    # ### end Alembic commands ###
