"""Initial migration

Revision ID: cfb3e25518d0
Revises: 
Create Date: 2020-10-10 21:46:13.917279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb3e25518d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=50), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_name'), 'location', ['name'], unique=True)
    op.create_table('satellite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cospar_id', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('decayed', sa.Boolean(), nullable=True),
    sa.Column('launch_date', sa.Date(), nullable=True),
    sa.Column('launch_year', sa.Integer(), nullable=True),
    sa.Column('mass', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('diameter', sa.Float(), nullable=True),
    sa.Column('span', sa.Float(), nullable=True),
    sa.Column('perigee', sa.Float(), nullable=True),
    sa.Column('apogee', sa.Float(), nullable=True),
    sa.Column('inclination', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cospar_id')
    )
    op.create_table('tle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tle1', sa.String(length=70), nullable=True),
    sa.Column('tle2', sa.String(length=70), nullable=True),
    sa.Column('epoch', sa.DateTime(), nullable=True),
    sa.Column('satellite_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['satellite_id'], ['satellite.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tle')
    op.drop_table('satellite')
    op.drop_index(op.f('ix_location_name'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###
