"""initial schema

Revision ID: 000aa99d1564
Revises: 
Create Date: 2025-02-24 13:02:13.613011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000aa99d1564'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satellite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('norad_id', sa.Integer(), nullable=True),
    sa.Column('intl_designator', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='CURRENT_TIMESTAMP', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decay_date', sa.Date(), nullable=True),
    sa.Column('launch_date', sa.Date(), nullable=True),
    sa.Column('launch_year', sa.Integer(), nullable=True),
    sa.Column('mass', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('diameter', sa.Float(), nullable=True),
    sa.Column('span', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_satellite_intl_designator'), 'satellite', ['intl_designator'], unique=True)
    op.create_index(op.f('ix_satellite_norad_id'), 'satellite', ['norad_id'], unique=True)
    op.create_table('orbit',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('epoch', sa.DateTime(timezone=True), nullable=False),
    sa.Column('satellite_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='CURRENT_TIMESTAMP', nullable=False),
    sa.Column('originator', sa.String(), nullable=False),
    sa.Column('originator_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ref_frame', sa.String(), nullable=True),
    sa.Column('time_system', sa.String(), nullable=True),
    sa.Column('mean_element_theory', sa.String(), nullable=True),
    sa.Column('eccentricity', sa.Float(), nullable=False),
    sa.Column('ra_of_asc_node', sa.Float(), nullable=False),
    sa.Column('arg_of_pericenter', sa.Float(), nullable=False),
    sa.Column('mean_anomaly', sa.Float(), nullable=False),
    sa.Column('ephemeris_type', sa.String(), nullable=True),
    sa.Column('element_set_no', sa.Integer(), nullable=True),
    sa.Column('rev_at_epoch', sa.Integer(), nullable=True),
    sa.Column('bstar', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('mean_motion', sa.Float(), nullable=False),
    sa.Column('mean_motion_dot', sa.Float(), nullable=False),
    sa.Column('mean_motion_ddot', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('perigee', sa.Float(), nullable=True),
    sa.Column('apogee', sa.Float(), nullable=True),
    sa.Column('inclination', sa.Float(), nullable=False),
    sa.Column('tle', sa.String(length=141), nullable=True),
    sa.ForeignKeyConstraint(['satellite_id'], ['satellite.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('satellite_id', 'epoch', 'originator', name='uix_satelliteid_epoch_originator')
    )
    op.create_index('ix_epoch', 'orbit', [sa.text('epoch DESC')], unique=False)
    op.create_index(op.f('ix_orbit_satellite_id'), 'orbit', ['satellite_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orbit_satellite_id'), table_name='orbit')
    op.drop_index('ix_epoch', table_name='orbit')
    op.drop_table('orbit')
    op.drop_index(op.f('ix_satellite_norad_id'), table_name='satellite')
    op.drop_index(op.f('ix_satellite_intl_designator'), table_name='satellite')
    op.drop_table('satellite')
    # ### end Alembic commands ###
