"""index on lowercase strings

Revision ID: 347036cd8450
Revises: 2645b2d61634
Create Date: 2025-03-07 21:17:19.767001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '347036cd8450'
down_revision: Union[str, None] = '2645b2d61634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_satellite_intl_designator', table_name='satellite')
    op.drop_index('ix_satellite_name', table_name='satellite')
    op.create_index('ix_satellite_name_lower', 'satellite', [sa.text('lower(name)')], unique=False)
    op.create_index('ix_satellite_intl_designator', 'satellite', [sa.text('lower(intl_designator')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_satellite_name_lower", table_name="satellite")
    op.drop_index('ix_satellite_intl_designator', table_name="satellite")
    op.create_index('ix_satellite_name', 'satellite', ['name'], unique=False)
    op.create_index('ix_satellite_intl_designator', 'satellite', ['intl_designator'], unique=False)
    # ### end Alembic commands ###
