name: Build and Push API Docker Image

on:
  push:
    branches: [ "main", "v2" ]

env:
  CR_URL: ewr.vutlrcr.com

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Login to Vultr Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CR_URL }}
          username: ${{ secrets.VULTR_CR_USERNAME }}
          password: ${{ secrets.VULTR_CR_PASSWORD }}

      - name: Setup Just runner
        uses: extractions/setup-just@v3
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}

      # - name: Build and push the Docker image
      #   uses: docker/build-push-action@v6
      #   with:
      #     tags: ewrpasspredict/


      # - run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)


      # -
